[global]
address = "0.0.0.0"
environment = "development"
db = "postgres://root:password@localhost:5432/wonders"
cache = "/etc/app/cache"
nasa_api_key = "xxxx-xxxx-xxxx-xxxx"
nasa_api_url = "https://api.nasa.gov/planetary/apod"

[development.server]
port = 8000

[staging.server]
port = 8000

[production.server]
port = 8000
